In [3]:
import pandas as pd
df=pd.read_csv("cars.csv")
df

,Id,year,brand,full_model_name,model_name,price,distance_travelled(kms),fuel_type,city,brand_rank,car_age
0,0,2016,Honda,Honda Brio S MT,Brio,425000.0,9680.0,Petrol,Mumbai,7,5.0
1,1,2012,Nissan,Nissan Sunny XV Diesel,Sunny,325000.0,119120.0,Diesel,Mumbai,11,9.0
2,2,2017,Toyota,Toyota Fortuner 2.8 4x2 MT [2016-2020],Fortuner,2650000.0,64593.0,Diesel,Thane,1,4.0
3,3,2017,Mercedes-Benz,Mercedes-Benz E-Class E 220d Expression [2019-...,E-Class,4195000.0,25000.0,Diesel,Mumbai,2,4.0
4,4,2012,Hyundai,Hyundai Verna Fluidic 1.6 CRDi SX,Verna,475000.0,23800.0,Diesel,Mumbai,14,9.0
...,...,...,...,...,...,...,...,...,...,...,...
1720,1720,2015,Hyundai,Hyundai Eon Era +,Eon,290000.0,38000.0,Petrol,Pune,14,6.0
1721,1721,2011,Bentley,Bentley Continental Flying Spur W12,Continental,7500000.0,36000.0,Petrol,Pune,44,10.0
1722,1722,2008,Mahindra-Renault,Mahindra-Renault Logan DLE 1.5 dci,Logan,185000.0,142522.0,Diesel,Pune,24,13.0
1723,1723,1990,Mahindra,Mahindra Jeep CJ 500 D,Jeep,325000.0,18581.0,Diesel,Pune,24,31.0
1724,1724,2017,Hyundai,Hyundai Creta SX Plus 1.6 AT CRDI,Creta,1395000.0,31028.0,Diesel,Pune,14,4.0

In [5]:
df.shape

(1725, 11)

In [223]:
# DATA PREPROCESSING

# 1. CONVERT NON-NUMERIC TO NUMERIC
#using LabelEncoder


from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df_2 = df
df_2['brand']= label_encoder.fit_transform(df_2['brand'])
df_2['model_name']= label_encoder.fit_transform(df_2['model_name'])
df_2['city']= label_encoder.fit_transform(df_2['city'])
df_2['fuel_type']= label_encoder.fit_transform(df_2['fuel_type'])
df_2['full_model_name']= label_encoder.fit_transform(df_2['full_model_name'])


##############df['Age'] = pd.to_numeric(df['Age'], errors='coerce') 

# 2. FIND VARIANCE AND CORRELATION
# if a columns values remains same there is not going to be much effect
# if there corelation is high between 2 columns ,any one need to be present.

print(df_2.var())
print(df_2.var().min())
df_var =df_2.drop('city',axis="columns")
######### inference fuel_type when removed reduced accuracy from 79 to 75

Id                         2.481125e+05
year                       1.028808e+01
brand                      8.461353e+01
full_model_name            4.718125e+04
model_name                 2.392481e+03
price                      2.794440e+12
distance_travelled(kms)    2.000374e+09
fuel_type                  1.017958e+00
city                       1.874791e+01
brand_rank                 1.677315e+02
car_age                    1.028808e+01
dtype: float64
1.0179582366589184

In [225]:
df_var

,Id,year,brand,full_model_name,model_name,price,distance_travelled(kms),fuel_type,brand_rank,car_age
0,0,2016,7,131,28,425000.0,9680.0,3,7,5.0
1,1,2012,23,570,129,325000.0,119120.0,1,11,9.0
2,2,2017,28,676,69,2650000.0,64593.0,1,1,4.0
3,3,2017,21,526,51,4195000.0,25000.0,1,2,4.0
4,4,2012,8,259,144,475000.0,23800.0,1,14,9.0
...,...,...,...,...,...,...,...,...,...,...
1720,1720,2015,8,221,59,290000.0,38000.0,3,14,6.0
1721,1721,2011,2,80,41,7500000.0,36000.0,3,44,10.0
1722,1722,2008,19,391,96,185000.0,142522.0,1,24,13.0
1723,1723,1990,18,347,89,325000.0,18581.0,1,24,31.0
1724,1724,2017,8,201,45,1395000.0,31028.0,1,14,4.0

In [227]:
print(df_2.corr())

                               Id      year     brand  full_model_name  \
Id                       1.000000 -0.054391  0.038418         0.033483
year                    -0.054391  1.000000  0.031594         0.015058
brand                    0.038418  0.031594  1.000000         0.983638
full_model_name          0.033483  0.015058  0.983638         1.000000
model_name               0.020867  0.016492  0.171926         0.250601
price                   -0.105696  0.288483 -0.112988        -0.079232
distance_travelled(kms)  0.100282 -0.386107  0.083600         0.086850
fuel_type               -0.078581 -0.062748 -0.015952        -0.017261
city                     0.122431 -0.158838  0.054782         0.050820
brand_rank               0.022191  0.134275  0.175707         0.112479
car_age                  0.054391 -1.000000 -0.031594        -0.015058

                         model_name     price  distance_travelled(kms)  \
Id                         0.020867 -0.105696                 0.100282
year                       0.016492  0.288483                -0.386107
brand                      0.171926 -0.112988                 0.083600
full_model_name            0.250601 -0.079232                 0.086850
model_name                 1.000000 -0.082217                 0.036930
price                     -0.082217  1.000000                -0.137351
distance_travelled(kms)    0.036930 -0.137351                 1.000000
fuel_type                 -0.014848 -0.259728                -0.232681
city                      -0.010279 -0.082369                 0.090316
brand_rank                 0.188761 -0.164591                -0.111406
car_age                   -0.016492 -0.288483                 0.386107

                         fuel_type      city  brand_rank   car_age
Id                       -0.078581  0.122431    0.022191  0.054391
year                     -0.062748 -0.158838    0.134275 -1.000000
brand                    -0.015952  0.054782    0.175707 -0.031594
full_model_name          -0.017261  0.050820    0.112479 -0.015058
model_name               -0.014848 -0.010279    0.188761 -0.016492
price                    -0.259728 -0.082369   -0.164591 -0.288483
distance_travelled(kms)  -0.232681  0.090316   -0.111406  0.386107
fuel_type                 1.000000 -0.009624    0.128372  0.062748
city                     -0.009624  1.000000    0.060534  0.158838
brand_rank                0.128372  0.060534    1.000000 -0.134275
car_age                   0.062748  0.158838   -0.134275  1.000000

In [254]:
# SPLIT DEPENDENT-INDEPENDENT VARIABLES
# TRAIN-TEST SPLIT 

X=df_2.drop("price",axis="columns")


Y=df_2[['price']] # double bracket so that a dataframe containing one column is created instead of just one column series
print(type(X))
print(type(Y))
X=df_var.drop("price",axis="columns")


Y=df_2[['price']]

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [256]:
X.loc[2,:]

Id                             2.0
year                        2017.0
brand                         28.0
full_model_name              676.0
model_name                    69.0
distance_travelled(kms)    64593.0
fuel_type                      1.0
brand_rank                     1.0
car_age                        4.0
Name: 2, dtype: float64

In [258]:
print(type(Y.loc[2,:]))

<class 'pandas.core.series.Series'>

In [260]:
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LinearRegression
from sklearn import linear_model

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [262]:
model=linear_model.LinearRegression()

In [264]:
model.fit(X_train,Y_train)

LinearRegression()

In [266]:
model.predict([X.loc[2,:]])

/home/admin1/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[2417503.89550847]])

In [268]:
y_pred=model.predict(X_test)
y_pred

array([[ 1.52365476e+06],
       [ 1.01710426e+06],
       [ 1.41426417e+06],
       [ 1.74167659e+06],
       [ 1.17955060e+06],
       [ 2.01131531e+06],
       [ 1.82866764e+06],
       [ 1.50994788e+06],
       [ 1.72464540e+06],
       [ 2.79629928e+05],
       [ 1.53889887e+06],
       [ 9.08741051e+05],
       [ 3.82644154e+05],
       [ 7.26364342e+05],
       [ 1.85761257e+06],
       [ 2.77614054e+06],
       [ 2.05668299e+06],
       [ 7.65577491e+05],
       [ 4.55494622e+05],
       [ 2.25284066e+05],
       [ 1.68543434e+06],
       [ 1.44594923e+06],
       [ 2.64198863e+06],
       [ 1.45687499e+06],
       [ 5.63099634e+05],
       [ 5.61201558e+05],
       [ 8.43851143e+05],
       [ 1.31567140e+06],
       [ 9.80748785e+05],
       [ 7.76384028e+05],
       [ 1.48522110e+06],
       [ 2.68809898e+06],
       [ 1.37840497e+06],
       [ 6.18368254e+05],
       [ 2.02197923e+06],
       [ 5.54471762e+05],
       [ 8.55628214e+05],
       [ 3.17334186e+05],
       [ 1.44401591e+06],
       [ 1.57523227e+06],
       [ 2.00846525e+06],
       [ 8.87509630e+05],
       [ 5.85996048e+05],
       [ 4.98948456e+05],
       [ 1.71963351e+05],
       [ 3.11911482e+05],
       [ 1.88401999e+06],
       [ 7.10929504e+05],
       [ 1.15912456e+06],
       [ 4.78729226e+05],
       [ 3.24935105e+06],
       [ 2.25508659e+06],
       [ 5.03048295e+05],
       [ 1.03447392e+06],
       [ 2.08560166e+06],
       [ 4.90268678e+05],
       [ 1.64044823e+06],
       [ 1.01982683e+06],
       [ 1.49394045e+06],
       [ 9.37464338e+05],
       [ 1.49276450e+06],
       [ 2.57457345e+06],
       [ 1.79244990e+06],
       [ 9.66553856e+05],
       [ 1.24298345e+06],
       [ 1.44065099e+06],
       [ 2.07115198e+06],
       [ 1.14169818e+05],
       [ 1.85485608e+06],
       [-5.27626173e+05],
       [ 2.95213037e+06],
       [ 2.15269268e+06],
       [ 1.15260760e+06],
       [ 1.42209746e+06],
       [ 3.50002342e+06],
       [ 2.05152213e+06],
       [ 1.79799148e+06],
       [ 1.79999839e+06],
       [ 9.78540547e+05],
       [ 2.85219561e+06],
       [ 7.20609727e+05],
       [ 2.45742063e+06],
       [ 2.72336551e+06],
       [ 1.28339507e+06],
       [ 1.08227211e+06],
       [-3.13275244e+04],
       [ 2.39477992e+05],
       [ 2.36758940e+06],
       [ 3.10450521e+06],
       [ 2.09113157e+06],
       [ 1.73265260e+06],
       [ 1.74556045e+06],
       [ 1.90171035e+06],
       [ 2.53575823e+06],
       [ 1.36346350e+06],
       [ 1.28811964e+06],
       [ 2.46505230e+05],
       [-1.56450300e+03],
       [ 1.59653533e+06],
       [ 1.05987617e+06],
       [ 1.57801443e+06],
       [ 1.40049561e+06],
       [ 1.06647084e+06],
       [ 1.30931479e+06],
       [ 1.91306155e+06],
       [ 3.42624173e+05],
       [ 1.36242492e+06],
       [ 2.90632348e+06],
       [ 1.11979865e+06],
       [ 1.23572000e+06],
       [ 3.48710827e+06],
       [-2.49965194e+04],
       [ 1.60084688e+06],
       [ 7.94414924e+05],
       [ 1.07549421e+06],
       [ 3.98785198e+05],
       [ 1.93051283e+06],
       [ 1.97151595e+06],
       [ 1.59174536e+06],
       [ 6.15842208e+05],
       [ 1.56214681e+06],
       [ 2.25646500e+06],
       [ 8.26367198e+05],
       [ 3.85723186e+05],
       [ 2.30485959e+06],
       [ 2.32127169e+06],
       [ 1.73223118e+06],
       [ 1.60692070e+06],
       [ 8.20202970e+05],
       [ 1.86591496e+06],
       [ 1.87345685e+06],
       [ 1.09134569e+06],
       [ 2.03632560e+06],
       [ 1.67411543e+06],
       [ 1.48303781e+06],
       [ 2.42672300e+06],
       [ 1.11858297e+06],
       [ 1.54495005e+06],
       [ 2.44341570e+06],
       [ 1.02976029e+06],
       [ 2.42233259e+06],
       [ 1.92159139e+06],
       [ 1.04127550e+06],
       [ 1.47129530e+06],
       [ 1.47023083e+06],
       [ 1.76414029e+06],
       [ 2.57183304e+06],
       [ 2.17267127e+06],
       [ 2.02838941e+06],
       [ 2.57498092e+06],
       [ 6.79546339e+05],
       [ 1.53217202e+06],
       [ 2.66406740e+06],
       [ 4.31693330e+05],
       [ 7.60843489e+05],
       [ 1.37939417e+06],
       [ 1.47483148e+06],
       [ 1.23198598e+06],
       [ 9.81656306e+05],
       [ 1.57042236e+06],
       [ 2.73032483e+06],
       [ 1.07045516e+06],
       [ 3.46324272e+05],
       [ 2.42917966e+06],
       [ 2.54753612e+06],
       [-3.44250801e+05],
       [ 3.23346164e+05],
       [ 2.16705056e+06],
       [ 2.08167194e+06],
       [ 1.37321476e+06],
       [ 1.52496881e+06],
       [ 2.59746698e+06],
       [ 9.61139178e+05],
       [ 1.94232444e+06],
       [ 1.87073112e+06],
       [ 2.45194687e+06],
       [ 2.58707803e+06],
       [ 2.65317715e+06],
       [ 3.31466899e+06],
       [ 9.58302776e+05],
       [ 9.16096076e+05],
       [ 4.31765344e+05],
       [ 1.93647575e+06],
       [ 2.43603537e+06],
       [ 7.61342393e+05],
       [ 1.66195058e+06],
       [ 1.19130863e+06],
       [ 1.51475572e+06],
       [ 3.23169539e+06],
       [ 4.93928811e+05],
       [ 2.65461194e+06],
       [ 1.01473885e+06],
       [ 1.52096977e+06],
       [ 1.63778172e+06],
       [ 1.67520941e+06],
       [ 6.53441653e+04],
       [ 2.79135233e+06],
       [-3.56025154e+05],
       [ 1.81618195e+06],
       [ 3.12895525e+06],
       [ 1.44416351e+06],
       [ 3.47585305e+05],
       [ 1.25078158e+06],
       [ 1.23284743e+06],
       [ 1.27665296e+06],
       [ 1.69570684e+06],
       [ 1.28146635e+06],
       [ 2.65772315e+06],
       [ 2.11897168e+06],
       [ 4.79048605e+05],
       [ 1.96276722e+06],
       [ 1.55384777e+06],
       [ 1.90394768e+06],
       [-2.45225491e+05],
       [ 2.37815211e+06],
       [ 1.44938145e+06],
       [ 1.77332466e+06],
       [ 3.02792689e+06],
       [-2.85248768e+05],
       [ 1.63468947e+06],
       [ 1.32895285e+06],
       [ 3.00438117e+06],
       [ 1.36493131e+06],
       [ 2.18678158e+06],
       [ 1.36773441e+06],
       [ 1.77395587e+06],
       [ 1.43053850e+06],
       [ 3.27507831e+06],
       [ 2.44369635e+06],
       [ 1.71776267e+06],
       [ 1.73060879e+06],
       [ 1.34099023e+06],
       [ 2.23289261e+06],
       [ 2.39541758e+06],
       [ 2.60316583e+06],
       [ 1.50481563e+06],
       [ 2.43819102e+06],
       [ 1.72862834e+06],
       [ 1.58090788e+06],
       [ 4.24518356e+05],
       [ 7.04468173e+05],
       [ 1.34247418e+06],
       [ 2.54429015e+06],
       [ 9.30320808e+05],
       [ 1.70074454e+06],
       [ 1.11951121e+06],
       [ 9.94235245e+05],
       [ 2.94097420e+05],
       [ 1.99614215e+06],
       [ 2.83585736e+06],
       [ 6.14212659e+05],
       [ 2.72227960e+05],
       [ 1.51978540e+06],
       [ 1.69276137e+06],
       [ 8.09386318e+05],
       [ 4.59295064e+05],
       [ 1.11623377e+06],
       [ 2.31898220e+06],
       [ 2.76611734e+06],
       [ 1.83259306e+06],
       [ 8.72053523e+05],
       [ 3.77113307e+05],
       [ 3.04307713e+06],
       [ 1.56005513e+06],
       [ 3.39592362e+05],
       [ 2.38270140e+06],
       [ 2.85319347e+06],
       [ 2.17547614e+06],
       [ 1.90894556e+06],
       [ 2.00270918e+06],
       [ 2.70514870e+06],
       [ 2.82137557e+06],
       [ 6.51583862e+05],
       [ 1.44567764e+06],
       [ 2.46037995e+06],
       [ 9.81411755e+05],
       [ 7.20517877e+05],
       [ 1.75787384e+06],
       [-7.59812217e+04],
       [ 1.00192111e+06],
       [ 2.20509676e+06],
       [ 2.13572521e+06],
       [ 1.97543158e+06],
       [ 9.12131602e+05],
       [ 2.92936185e+06],
       [ 2.31252392e+06],
       [ 1.92142292e+06],
       [ 1.29970088e+06],
       [ 1.92744640e+06],
       [ 2.22789770e+06],
       [ 3.00034297e+06],
       [ 2.10253266e+06],
       [ 1.18054153e+06],
       [ 2.13936810e+06],
       [ 7.79180212e+05],
       [ 1.66559497e+06],
       [ 2.32176937e+06],
       [ 2.07975575e+06],
       [ 3.20001814e+06],
       [ 2.52425365e+06],
       [ 1.87264722e+06],
       [ 1.16929988e+06],
       [ 9.72441249e+04],
       [ 1.42874314e+06],
       [ 2.04411762e+06],
       [ 1.58703564e+06],
       [ 1.62256939e+06],
       [ 1.97122983e+06],
       [ 1.63560479e+06],
       [ 2.09875836e+06],
       [ 9.64603696e+05],
       [ 2.71461437e+06],
       [ 1.98134337e+06],
       [ 1.82377924e+06],
       [ 3.04013456e+06],
       [ 1.68537938e+06],
       [ 1.64035905e+06],
       [ 1.47044012e+06],
       [ 2.51277439e+06],
       [ 2.29744430e+06],
       [ 1.83834232e+06],
       [ 1.41042609e+06],
       [ 3.35447620e+06],
       [ 6.97439169e+05],
       [ 9.12714046e+05],
       [ 3.09417950e+06],
       [ 2.34455413e+06],
       [ 2.27866434e+06],
       [ 6.09804020e+05],
       [-2.29132748e+05],
       [ 1.14517439e+06],
       [ 5.86757454e+05],
       [ 2.53761742e+06],
       [ 1.14359160e+06],
       [ 1.52869363e+06],
       [ 1.97974956e+06],
       [ 1.33509420e+06],
       [ 1.31133088e+06],
       [ 1.50821106e+06],
       [ 1.97353983e+06],
       [ 2.53446181e+06],
       [ 9.76320841e+05],
       [ 2.38109135e+06],
       [ 2.78785032e+06],
       [ 1.08291629e+06]])

In [270]:
y_df=pd.DataFrame({'res':y_pred[:,0]})
y_pred[2,0]

1414264.1700063795

In [272]:

from sklearn.metrics import mean_absolute_percentage_error
print(mean_absolute_percentage_error(y_df,Y_test))
print(type(y_df))
print(type(Y_test))
#df_d
print(y_df.shape)
print(Y_test.shape)

0.9679740666148704
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(345, 1)
(345, 1)

In [250]:
#96.81--city removed