In [3]:
import pandas as pd
df=pd.read_csv("cars.csv")
df

,Id,year,brand,full_model_name,model_name,price,distance_travelled(kms),fuel_type,city,brand_rank,car_age
0,0,2016,Honda,Honda Brio S MT,Brio,425000.0,9680.0,Petrol,Mumbai,7,5.0
1,1,2012,Nissan,Nissan Sunny XV Diesel,Sunny,325000.0,119120.0,Diesel,Mumbai,11,9.0
2,2,2017,Toyota,Toyota Fortuner 2.8 4x2 MT [2016-2020],Fortuner,2650000.0,64593.0,Diesel,Thane,1,4.0
3,3,2017,Mercedes-Benz,Mercedes-Benz E-Class E 220d Expression [2019-...,E-Class,4195000.0,25000.0,Diesel,Mumbai,2,4.0
4,4,2012,Hyundai,Hyundai Verna Fluidic 1.6 CRDi SX,Verna,475000.0,23800.0,Diesel,Mumbai,14,9.0
...,...,...,...,...,...,...,...,...,...,...,...
1720,1720,2015,Hyundai,Hyundai Eon Era +,Eon,290000.0,38000.0,Petrol,Pune,14,6.0
1721,1721,2011,Bentley,Bentley Continental Flying Spur W12,Continental,7500000.0,36000.0,Petrol,Pune,44,10.0
1722,1722,2008,Mahindra-Renault,Mahindra-Renault Logan DLE 1.5 dci,Logan,185000.0,142522.0,Diesel,Pune,24,13.0
1723,1723,1990,Mahindra,Mahindra Jeep CJ 500 D,Jeep,325000.0,18581.0,Diesel,Pune,24,31.0
1724,1724,2017,Hyundai,Hyundai Creta SX Plus 1.6 AT CRDI,Creta,1395000.0,31028.0,Diesel,Pune,14,4.0

In [5]:
df.shape

(1725, 11)

In [7]:
# DATA PREPROCESSING

# 1. CONVERT NON-NUMERIC TO NUMERIC
#using LabelEncoder


from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
df_2 = df
df_2['brand']= label_encoder.fit_transform(df_2['brand'])
df_2['model_name']= label_encoder.fit_transform(df_2['model_name'])
df_2['city']= label_encoder.fit_transform(df_2['city'])
df_2['fuel_type']= label_encoder.fit_transform(df_2['fuel_type'])
df_2['full_model_name']= label_encoder.fit_transform(df_2['full_model_name'])


##############df['Age'] = pd.to_numeric(df['Age'], errors='coerce') 


df_2

,Id,year,brand,full_model_name,model_name,price,distance_travelled(kms),fuel_type,city,brand_rank,car_age
0,0,2016,7,131,28,425000.0,9680.0,3,9,7,5.0
1,1,2012,23,570,129,325000.0,119120.0,1,9,11,9.0
2,2,2017,28,676,69,2650000.0,64593.0,1,14,1,4.0
3,3,2017,21,526,51,4195000.0,25000.0,1,9,2,4.0
4,4,2012,8,259,144,475000.0,23800.0,1,9,14,9.0
...,...,...,...,...,...,...,...,...,...,...,...
1720,1720,2015,8,221,59,290000.0,38000.0,3,13,14,6.0
1721,1721,2011,2,80,41,7500000.0,36000.0,3,13,44,10.0
1722,1722,2008,19,391,96,185000.0,142522.0,1,13,24,13.0
1723,1723,1990,18,347,89,325000.0,18581.0,1,13,24,31.0
1724,1724,2017,8,201,45,1395000.0,31028.0,1,13,14,4.0

In [9]:
# SPLIT DEPENDENT-INDEPENDENT VARIABLES
# TRAIN-TEST SPLIT 

X=df_2.drop("price",axis="columns")


Y=df_2[['price']] # double bracket so that a dataframe containing one column is created instead of just one column series
print(type(X))
print(type(Y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [11]:
X.loc[2,:]

Id                             2.0
year                        2017.0
brand                         28.0
full_model_name              676.0
model_name                    69.0
distance_travelled(kms)    64593.0
fuel_type                      1.0
city                          14.0
brand_rank                     1.0
car_age                        4.0
Name: 2, dtype: float64

In [27]:
df12=Y.loc[2,:]
print(type(df12))

<class 'pandas.core.series.Series'>

In [29]:
from sklearn.model_selection import train_test_split
#from sklearn.linear_model import LinearRegression
from sklearn import linear_model


X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [31]:
model=linear_model.LinearRegression()

In [39]:
model.fit(X_train,Y_train)

LinearRegression()

In [45]:
model.predict([X.loc[2,:]])

/home/admin1/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[2395020.84085926]])

In [75]:
y_pred=model.predict(X_test)
y_pred

array([[1486467.10818338],
       [1047347.60399579],
       [1414644.57160348],
       [1699829.83983245],
       [1155594.73745872],
       [2025008.99707937],
       [1804461.18218684],
       [1505078.90866613],
       [1754396.55251932],
       [ 295211.60150415],
       [1499713.20496339],
       [ 912311.62006031],
       [ 337500.78346531],
       [ 750943.53660262],
       [1877381.99211666],
       [2781320.30335204],
       [2084876.3278219 ],
       [ 730630.15764444],
       [ 422267.89793278],
       [ 184288.91029702],
       [1680235.16567789],
       [1442372.84929697],
       [2600494.79701303],
       [1409061.33049364],
       [ 573733.01988   ],
       [ 589296.64526358],
       [ 852238.08992149],
       [1350835.80514924],
       [1013423.57126081],
       [ 802367.12172382],
       [1484153.02456096],
       [2691984.60062778],
       [1347502.1802405 ],
       [ 650143.22827917],
       [2022647.28073657],
       [ 580165.0947924 ],
       [ 879589.06776112],
       [ 276317.23679663],
       [1441248.5526343 ],
       [1592875.51659945],
       [2032230.91828367],
       [ 898027.42952794],
       [ 614834.76686469],
       [ 455030.97050257],
       [ 199950.07749313],
       [ 343857.5600968 ],
       [1907645.40969163],
       [ 739157.32485732],
       [1181608.40692803],
       [ 502805.22912703],
       [3217744.52916242],
       [2206183.99205567],
       [ 501803.45509715],
       [1041724.4310057 ],
       [2076960.76346363],
       [ 511676.77591671],
       [1664132.25220519],
       [1050019.29114915],
       [1521438.06471381],
       [ 896222.68039401],
       [1518366.81527899],
       [2571773.83678062],
       [1768902.29580665],
       [ 997658.65179431],
       [1248311.10900559],
       [1398920.26825996],
       [2065938.51025608],
       [  75821.2869963 ],
       [1853289.21219373],
       [-484862.43456906],
       [2959649.08241086],
       [2147371.87808864],
       [1096688.7886088 ],
       [1445854.3980424 ],
       [3502637.82491224],
       [2077394.92539613],
       [1745587.54058461],
       [1831672.34297173],
       [ 979222.97869061],
       [2824813.57892177],
       [ 748656.6569581 ],
       [2479093.23217994],
       [2745928.59424247],
       [1277760.53553542],
       [1108502.9727366 ],
       [ -71761.82752974],
       [ 276458.6041583 ],
       [2320975.10091841],
       [3121186.21560068],
       [2116194.75858429],
       [1753205.95550345],
       [1701500.79485171],
       [1889974.19432586],
       [2544735.10388871],
       [1388180.43953468],
       [1292672.21820427],
       [ 271070.90809545],
       [  34627.35314855],
       [1617703.08433211],
       [1065601.95553103],
       [1591968.13588305],
       [1368785.74458849],
       [1089446.31361113],
       [1317807.06578636],
       [1935682.28731874],
       [ 301586.10214917],
       [1360395.99660484],
       [2916760.68771073],
       [1143017.37026858],
       [1267162.37075293],
       [3487193.24208635],
       [ -72390.7997108 ],
       [1560902.32915382],
       [ 791543.66119239],
       [1082488.99190082],
       [ 378083.57266012],
       [1948001.7719036 ],
       [1983225.53910723],
       [1595636.66976549],
       [ 617491.14387126],
       [1563648.58540107],
       [2280869.49539053],
       [ 843341.94711158],
       [ 416289.96736532],
       [2328100.43386886],
       [2329435.97726879],
       [1722481.92207542],
       [1625913.46189107],
       [ 814095.12545189],
       [1895935.45074806],
       [1893415.49082118],
       [1068621.34382442],
       [2059510.98680474],
       [1626171.64563286],
       [1511993.78752717],
       [2455442.22371975],
       [1100179.04830433],
       [1570573.86927859],
       [2451620.32678457],
       [ 968311.48832585],
       [2413554.80830087],
       [1912967.80217607],
       [1059623.16698217],
       [1430224.64605589],
       [1497250.89962564],
       [1722408.02667974],
       [2521941.9728114 ],
       [2194739.99674439],
       [2035341.90464365],
       [2549212.17414691],
       [ 699309.47766137],
       [1552921.11722657],
       [2687342.56708097],
       [ 462910.3406333 ],
       [ 755504.98579468],
       [1403189.03164452],
       [1490376.10832021],
       [1239234.18695186],
       [1014314.13364525],
       [1547687.64770569],
       [2748522.80592892],
       [1092348.06329465],
       [ 379025.43408193],
       [2420500.37794848],
       [2521994.269942  ],
       [-309105.07475317],
       [ 336585.15633872],
       [2148838.17196327],
       [2104069.61729589],
       [1404383.84570429],
       [1547214.917721  ],
       [2604554.14376803],
       [ 950344.13527562],
       [1914454.62997384],
       [1870935.39218967],
       [2464378.50847425],
       [2612020.93135484],
       [2676655.81846759],
       [3339410.73668702],
       [ 951413.48922816],
       [ 911360.8549625 ],
       [ 442242.64168505],
       [1875196.59123507],
       [2460320.59181958],
       [ 726474.19985034],
       [1616420.20392744],
       [1165312.1352894 ],
       [1473313.82989304],
       [3232607.64318426],
       [ 504620.96513222],
       [2664692.39855996],
       [1039091.78649066],
       [1521101.37903832],
       [1577581.3141827 ],
       [1707221.1725364 ],
       [  26845.21884821],
       [2811365.62517583],
       [-387970.0559926 ],
       [1837667.9472104 ],
       [3118958.15784778],
       [1473443.7235734 ],
       [ 305939.06672855],
       [1229392.94054037],
       [1190309.05084758],
       [1281980.38158345],
       [1725177.78911766],
       [1309042.58287129],
       [2677277.815173  ],
       [2111904.61008818],
       [ 473261.86759214],
       [1968968.27235848],
       [1545271.78808604],
       [1888613.95507535],
       [-281375.59690785],
       [2362183.30983655],
       [1477579.40755861],
       [1759501.72257166],
       [2994778.00268985],
       [-284194.67587137],
       [1655726.70989969],
       [1348047.40049021],
       [3015596.01242128],
       [1335220.03619258],
       [2175461.878692  ],
       [1366937.62629496],
       [1742264.9393252 ],
       [1427473.23596646],
       [3281814.87890056],
       [2465412.07013129],
       [1741217.50382918],
       [1688259.4020732 ],
       [1319352.0121884 ],
       [2241349.37925376],
       [2419722.93086241],
       [2586399.47825682],
       [1523159.62830491],
       [2462144.10928044],
       [1757609.98865597],
       [1597408.67017317],
       [ 450705.33885987],
       [ 659447.6380922 ],
       [1338721.4738759 ],
       [2531604.11336237],
       [ 931546.91137794],
       [1647623.13706256],
       [1135158.95501596],
       [1021165.31882142],
       [ 308172.49410698],
       [2022099.94368434],
       [2833505.99086343],
       [ 573117.74597844],
       [ 227363.90695438],
       [1510085.97167437],
       [1682561.24928461],
       [ 836831.89752574],
       [ 419839.93899904],
       [1072540.80044845],
       [2334982.33377881],
       [2772276.08323902],
       [1849962.89637807],
       [ 895459.80937082],
       [ 358159.99650107],
       [3061622.52731882],
       [1586811.23413868],
       [ 294383.32501562],
       [2405770.26252697],
       [2851262.82019535],
       [2176270.33266617],
       [1869917.0827096 ],
       [1961309.78591402],
       [2669949.91816245],
       [2838865.6090782 ],
       [ 616094.10290715],
       [1468427.4036237 ],
       [2485271.37652114],
       [ 972039.0378897 ],
       [ 747850.99830766],
       [1776639.9267251 ],
       [ -38398.76237628],
       [ 962938.84980901],
       [2199354.22416359],
       [2161687.34872316],
       [1965215.53691855],
       [ 938959.80309109],
       [2953156.0206309 ],
       [2333190.47765033],
       [1948776.97403139],
       [1330070.12954798],
       [1877856.67791398],
       [2215957.81898904],
       [2985885.55184026],
       [2044968.51201817],
       [1195792.52015452],
       [2129035.21812582],
       [ 807114.56911087],
       [1686421.85565862],
       [2274512.19175856],
       [2097432.8954535 ],
       [3201874.500771  ],
       [2515106.95172134],
       [1893192.79483226],
       [1191453.41784708],
       [ 126627.10784017],
       [1438478.38043785],
       [2054470.52986315],
       [1613213.88126522],
       [1655001.75108162],
       [1995151.59564619],
       [1658453.00556189],
       [2089432.63046685],
       [ 958473.44338654],
       [2741300.29821922],
       [1920744.88405581],
       [1792924.02002437],
       [3044072.70693509],
       [1639314.17919835],
       [1597195.25943522],
       [1487862.37348129],
       [2540754.79913193],
       [2317212.5975991 ],
       [1862359.31766576],
       [1432057.15186328],
       [3356202.76000166],
       [ 643290.41265918],
       [ 936393.76542404],
       [3084323.51562247],
       [2344079.0570675 ],
       [2230246.33035938],
       [ 566045.66637896],
       [-262013.41975121],
       [1165671.03294761],
       [ 618059.18178153],
       [2538100.87958412],
       [1152113.72750422],
       [1514429.03940131],
       [1952794.45854199],
       [1364802.0625415 ],
       [1338383.82125033],
       [1539081.31204467],
       [1944841.75071234],
       [2510535.10865732],
       [ 979264.0814472 ],
       [2402907.67416257],
       [2750370.93070705],
       [1040305.86397994]])

In [115]:
y_df=pd.DataFrame({'res':[y_pred[2,0]]})
y_pred[2,0]

1414644.571603477

In [107]:

from sklearn.metrics import mean_absolute_percentage_error
print(mean_absolute_percentage_error(y_df,Y_test))
print(type(y_df))
print(type(Y_test))
#df_d
print(y_df.shape)
print(Y_test.shape)

0.7981456197214164
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
(345, 1)
(345, 1)